name: Deploy static site to Azure Web App - MyFirstWebAap

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  deploy:
    runs-on: windows-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Login to Azure
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZUREAPPSERVICE_CLIENTID_A2A9A01060674AFF8E5BC2143E1FA417 }}
          tenant-id: ${{ secrets.AZUREAPPSERVICE_TENANTID_2B30A60715894D03B4DE437BBDED144B }}
          subscription-id: ${{ secrets.AZUREAPPSERVICE_SUBSCRIPTIONID_D20DF43FA7B142C8AAC69217A8B98B43 }}

      - name: Deploy to Azure Web App
        uses: azure/webapps-deploy@v3
        with:
          app-name: 'MyFirstWebAap'
          slot-name: 'Production'
          package: .
