name: Build and deploy ASP.Net Core app to Azure Web App - MyFirstWebAap

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest
    permissions:
      contents: read

    steps:
      - uses: actions/checkout@v4

      - name: Set up .NET Core
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '8.x'

      - name: Restore dependencies
        run: dotnet restore EcommerceWebsite/EcommerceWebsite.csproj

      - name: Build with dotnet
        run: dotnet build EcommerceWebsite/EcommerceWebsite.csproj --configuration Release

      - name: dotnet publish
        run: dotnet publish EcommerceWebsite/EcommerceWebsite.csproj -c Release -o "${{env.DOTNET_ROOT}}/myapp"

      - name: Upload artifact for deployment job
        uses: actions/upload-artifact@v4
        with:
          name: .net-app
          path: ${{env.DOTNET_ROOT}}/myapp

  deploy:
    runs-on: windows-latest
    needs: build
    permissions:
      id-token: write
      contents: read

    steps:
      - name: Download artifact from build job
        uses: actions/download-artifact@v4
        with:
          name: .net-app

      - name: Login to Azure
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZUREAPPSERVICE_CLIENTID_306329E2B35A46B4822E5CD9778D8C37 }}
          tenant-id: ${{ secrets.AZUREAPPSERVICE_TENANTID_2E46FB1A2C284492A4BC872780EFB2D9 }}
          subscription-id: ${{ secrets.AZUREAPPSERVICE_SUBSCRIPTIONID_A2ED148834D8460088A86EED71E60D79 }}

      - name: Deploy to Azure Web App
        id: deploy-to-webapp
        uses: azure/webapps-deploy@v3
        with:
          app-name: 'MyFirstWebAap'
          slot-name: 'Production'
          package: .
